typography_spectrum: 1
color:
  brandColors:
    - '#f0e7da'
    - '#b19073'
    - '#8a4d4d'
    - '#ea465d'
    - '#46af7c'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75058
analytics:
  google: null
  facebook: null
  twitter: null
name: creatinglavie
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Creating Lavie
description: on a quest for great food packaging
purpose: []
