name: creatinglavie
favicon: null
layout_spectrum: 0.75058
typography_spectrum: 1
title: Creating Lavie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0e7da'
    - '#b19073'
    - '#8a4d4d'
    - '#ea465d'
    - '#46af7c'
  brandStrength: 0.625
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
