name: creatinglavie
favicon: null
layout_spectrum: 0.4431461759377271
typography_spectrum: 0.14219650300219655
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.36776875075884163
  lightness: 0.5142399468459189
  saturation: 0.19961031922139227
  rhythmicContrast: 0.29878953960724175
purpose: []
